version : '3.0'

services:
  main:
    container_name: main2
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 2001:2001
    command: npm run dev
    restart: always